### ISSUE TITLE
Quest NPC collision bug

### ISSUE THREAD

**Issue by grandao** [Asunaya/RefinedGunz#7] opened 2016-12-19 01:19 UTC
It seems NPC in quest game mode can't hit you, also their movement seems buggy.

**Comment by Asunaya** [comment] 2017-01-07 23:41
22df3a5 fixed the movement bug, and the inability to hit players seems to have been caused by their items not being in zitem.xml. I've added those in the system.mrs in release v0.4.0, so should be fixed now.

**Closed by Asunaya** 2017-01-07 23:41 UTC
